repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-unused-variable', '--ignore-init-module-imports', '--remove-all-unused-imports']

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
      - id: pyupgrade
        args: ['--py3-plus']

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3.8

#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.9.2
#    hooks:
#      - id: flake8
#        additional_dependencies: [
#          'flake8-blind-except',
#          'flake8-bandit',
#          'flake8-comprehensions',
#          'flake8-mutable',
#          'flake8-bugbear',
#        ]
